# Generated by Django 5.0.4 on 2025-04-30 16:29

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentapplication',
            name='applicant_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload a recent portrait photo.', null=True, upload_to='applicant_images/'),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='disability_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='employment_status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Retired', 'Retired')], default='Employed', max_length=20),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='has_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='has_pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='id_number_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Upload a clear photo of your ID.', null=True, upload_to='id_numbers/'),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your gross monthly income in USD.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='number_of_children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='pet_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='references',
            field=models.TextField(blank=True, help_text='Please provide 2 references and their contacts.', null=True),
        ),
    ]
