# Generated by Django 5.0.4 on 2025-02-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_amenity_alter_user_role_property_propertyimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('House Provider', 'House Provider')], max_length=30),
        ),
    ]
