# Generated by Django 5.0.4 on 2025-02-02 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='amenity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
