# Generated by Django 5.0.4 on 2025-02-02 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_amenity_created_at_amenity_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
