# Generated by Django 5.0.4 on 2025-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_property_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='Kigali Rwanda', max_length=255),
        ),
    ]
