# Generated by Django 5.0.4 on 2025-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Office', 'Office')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, choices=[('Rebero', 'Rebero'), ('Gacuriro', 'Gacuriro'), ('Nyamirambo', 'Nyamirambo'), ('Nyamata', 'Nyamata'), ('Gisenyi', 'Gisenyi')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured'), ('Rent', 'Rent'), ('Sale', 'Sale')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
