# Generated by Django 5.0.4 on 2025-02-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_property_bathroom_property_category_property_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, choices=[('Rebero', 'Rebero'), ('Gacuriro', 'Gacuriro'), ('Nyamirambo', 'Nyamirambo'), ('Nyamata', 'Nyamata'), ('Gisenyi', 'Gisenyi'), ('Kacyiru', 'Kacyiru'), ('Kabeza', 'Kabeza'), ('Kicukiro', 'Kicukiro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertyreview', to='backend.property'),
        ),
    ]
