# Generated by Django 5.0.4 on 2025-02-12 21:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_property_city_alter_propertyreview_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='The start date of the rental contract.')),
                ('end_date', models.DateField(help_text='The end date of the rental contract.')),
                ('rental_period_months', models.PositiveIntegerField(help_text='The length of the rental period in months.')),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Monthly rent amount.', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, help_text='Security deposit amount.', max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', help_text='The current payment status of the contract.', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Expired', 'Expired'), ('Pending', 'Pending')], default='Pending', help_text='The current status of the contract (e.g., Active, Terminated).', max_length=10)),
                ('signed_date', models.DateField(blank=True, help_text='The date when both parties signed the contract.', null=True)),
                ('additional_terms', models.TextField(blank=True, help_text='Any additional terms or agreements in the contract.', null=True)),
                ('rent_due_date', models.DateField(help_text='The date when the rent is due each month.')),
                ('payment_method', models.CharField(blank=True, help_text='The agreed method of payment (e.g., Bank Transfer, Cash).', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_provider_contracts', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='backend.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contracts',
                'ordering': ['start_date'],
            },
        ),
    ]
