# Generated by Django 5.0.4 on 2025-02-12 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
