# Generated by Django 5.0.4 on 2025-02-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_contract_agent'),
        ('frontend', '0003_alter_rentapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='rent_application',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='frontend.rentapplication'),
            preserve_default=False,
        ),
    ]
