# Generated by Django 5.0.4 on 2025-02-12 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_contract_rent_application'),
        ('frontend', '0003_alter_rentapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='rent_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='frontend.rentapplication'),
        ),
    ]
