# Generated by Django 5.0.4 on 2025-03-19 19:27

import backend.models
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_contract_rent_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=backend.models.category_image_path)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
