# Generated by Django 5.0.4 on 2025-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_property_nearby_gym_property_nearby_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
