# Generated by Django 5.0.4 on 2025-04-24 10:19

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='map_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='video_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='video_thumbnail'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
