# Generated by Django 5.0.4 on 2025-02-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentapplication',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='rentapplication',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='rentapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rentapplication',
            name='rejected_at',
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='preferred_move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentapplication',
            name='rental_period_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentapplication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
