# Generated by Django 5.0.4 on 2025-02-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_applied_at_rentapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Moved Out', 'Moved Out')], default='Pending', max_length=10),
        ),
    ]
