# Generated by Django 5.0.4 on 2025-04-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_rentapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentapplication',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rentapplication',
            name='user',
        ),
    ]
